### ISSUE TITLE
tools crash

### ISSUE THREAD

**Issue by frank-lgtm** [lakeleisu/mongo-compare#1]
When I used the random mode to verify the data, the following error was prompted
![image](https://user-images.githubusercontent.com/81206575/112086906-03e52100-8bc8-11eb-8f59-ef301e4004b5.png)

I found that this problem will recur when the -c parameter is not set

**Comment by lakeleisu** [comment]
This may be a bug, I need to fix it

**Comment by lakeleisu** [comment]
fix，https://github.com/lakeleisu/mongo-compare/commit/90d94f570188b0d699f753a9a785ff9a49ed72d8
